FROM node:20-alpine AS base

WORKDIR /app
ENV CI=true

COPY server/package*.json ./
RUN npm ci

FROM base AS dev

COPY server/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]

FROM base AS build

COPY server/ ./
RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app
ENV NODE_ENV=production

COPY server/package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["npm", "run", "start"]
